image: gcr.io/google-samples/microservices-demo/currencyservice
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "true"
readinessProbeArg: "-addr=:7000"
livenessProbeArg: "-addr=:7000"

servicePort: 7000