image: gcr.io/google-samples/microservices-demo/paymentservice
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "true"
readinessProbeArg: "-addr=:50051"
livenessProbeArg: "-addr=:50051"

servicePort: 50051
