replicaCount: 3
registrySecret: my-registry-key
appContainerName: javamysqlapp
appImage: fsiegrist/fesi-repo
imageVersion: bootcamp-java-mysql-project-1.2-SNAPSHOT
containerPort: 8080

servicePort: 8080

configName: db-config
configData:
  DB_SERVER: my-release-mysql-primary

secretName: db-secret
secretData: 
  DB_USER: my-user
  DB_PWD: my-pass
  DB_NAME: my-app-db
  MYSQL_ROOT_PASSWORD: secret-root-pass

regularData: {}
 # MY_ENV: my-value

ingress:
  hostName: java-mysql-app.com # set this value to Linode nodebalancer address for LKE
  pathType: Prefix
  path: /
